package com.silb.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import lombok.Data;

/**
 * Simple message bean
 * <p>
 * Takes an int for unique, autogenerated ID and two String values for Message
 * content and user name
 * </p>
 * 
 * @author bish0p
 *
 */
@Entity
public class Message {

	private @Id @GeneratedValue Long id;
	private String content;
	private String user;

	private	 Message() {
	}
	
	public Message(String content, String user) {
		this.setContent(content);
		this.setUser(user);
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}
	
	

}
