package com.silb.model;

/**
 * Simple message bean
 * <p>
 * Takes an int for unique, autogenerated ID and two String values for Message
 * content and user name
 * </p>
 * 
 * @author bish0p
 *
 */
public class Message {

	private int id;
	private String message;
	private String user;

	public Message() {
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
