package com.silb.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import lombok.Data;

/**
 * Simple message bean
 * <p>
 * Takes a Long for unique, autogenerated ID and two String values for Message
 * content and user name
 * </p>
 * 
 * @author bish0p
 *
 */
@Data
@Entity
public class Message {

	private @Id @GeneratedValue Long id;
	private String message;
	private String user;

	public Message() {
	}

	public Message(String message, String user) {
		this.message = message;
		this.user = user;
	}

}
